notifications:
  email: false

language: python

python: 3.6

env:
  - ANSIBLE_VER=2.6.1 TESTINFRA_VER=1.14.0

sudo: true

stages:
  - lint
  - test
  - non-functional-test

services:
  - docker

before_install:
  - docker-compose -f tests/docker-compose.yml build
  - sudo mkdir -p /etc/ansible/roles
  - sudo ln -s $TRAVIS_BUILD_DIR /etc/ansible/roles/user_management
  - sudo cp -f $TRAVIS_BUILD_DIR/tests/inventory /etc/ansible/hosts
  # Set host_key_checking = false
  - echo "W2RlZmF1bHRzXQ0KaG9zdF9rZXlfY2hlY2tpbmcgPSBmYWxzZQ==" | base64 -d > ~/.ansible.cfg

install:
  - sudo apt-get install sshpass
  - pip install pytest
  - pip install ansible==$ANSIBLE_VER
  - pip install testinfra==$TESTINFRA_VER

script:
  - docker-compose -f tests/docker-compose.yml up -d &> /dev/null
  - ansible-playbook tests/test-install.yml -v || true
  - py.test --hosts='ansible://containers' --ansible-inventory='/etc/ansible/hosts' tests/test-install_spec.py || exit 1
  - docker-compose -f tests/docker-compose.yml down &> /dev/null

jobs:
  allow_failures:
    - script:
        - ansible-lint -p .

  include:
    - stage: lint
      before_install: []
      install:
        - pip install ansible-lint
      script:
        - ansible-lint -p .

    # Ensure check mode works
    - stage: non-functional-test
      before_script:
        - docker-compose -f tests/docker-compose.yml up -d
      script:
        - ansible-playbook tests/test-install.yml --check --diff

    # Idempotency test
    - stage: non-functional-test
      before_script:
        - docker-compose -f tests/docker-compose.yml up -d
        - ansible-playbook tests/test-install.yml
      script:
        - '! ansible-playbook tests/test-install.yml | grep "changed=" | grep -v "changed=0"'
