---

- name: Install Samba
  package:
    name: samba
    state: present
  when: not ansible_check_mode

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Send over samba configuration file
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: 0644
  notify:
    - restart samba

- name: Start and enable samba
  service:
    name: smbd
    state: started
    enabled: true
